stateDiagram-v2
classDef common fill: white, stroke: black, text-align: center
s1_1::: common: Program#58;enter\nExpressionStatement#58;enter\nLiteral (use strict)\nExpressionStatement#58;exit\nExpressionStatement#58;enter\nLiteral (0)\nExpressionStatement#58;exit\nProgram#58;exit
[*] --> s1_1
s1_1 --> [*]
