stateDiagram-v2
classDef common fill: white, stroke: black, text-align: center
classDef unreachable fill: #FF9800, stroke-dasharray: 5 5
classDef thrown fill: none, line-height: 1, stroke: none
s1_1::: common: <b>s1_1</b>\nProgram#58;enter\nIfStatement#58;enter\nIdentifier (foo)
s1_2::: common: <b>s1_2</b>\nThrowStatement#58;enter\nIdentifier (bar)\nThrowStatement#58;exit
s1_4::: common: <b>s1_4</b>\nIfStatement#58;exit\nProgram#58;exit
s1_3:::common: #60;#60;unreachable#62;#62;\n<b>s1_3</b>
s1_3:::unreachable
thrown:::thrown: ✘
[*] --> s1_1
s1_1 --> s1_2
s1_1 --> s1_4
s1_2 --> s1_3
s1_3 --> s1_4
s1_4 --> [*]
s1_2 --> thrown
