stateDiagram-v2
classDef common fill: white, stroke: black, text-align: center
s2_1::: common: FunctionDeclaration#58;enter\nIdentifier (foo)\nBlockStatement\nFunctionDeclaration#58;exit
[*] --> s2_1
s2_1 --> [*]
