stateDiagram-v2
classDef common fill: white, stroke: black
class s2_1 common
state "FunctionDeclaration:enter\nIdentifier (foo)\nBlockStatement\nFunctionDeclaration:exit" as s2_1
[*] --> s2_1
s2_1 --> [*]
