name: Node.js CI

on: [push, pull_request]

jobs:

  lint:

    name: Lint Files

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ^20.8
    - run: |
        npm install
        npm run lint

  test:

    name: Test (Node.js ${{ matrix.node-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12.22.0', '12', '14.17.0', '14', '16.0.0', '16', '18', '20', '21']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm test

  test-eslint-8_4:

    name: Test (ESLint 8.4)

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: |
        npm install --force eslint@8.4
        npm test
